ENCRYPTED_STRIPE_TOKEN = 'encrypted-token'
ENCRYPTED_DATABASE_PASSWORD = 'encrypted-password'
ENCRYPTED_MAIL_USERNAME = 'encrypted-mail-username'
ENCRYPTED_MAIL_PASSWORD = 'encrypted-mail-password'

ENCRYPTED_SESSION_KEY = 'session-key-salt'
ENCRYPTED_ADMIN_PASSPHRASE = "encrypted-admin-password"

DATABASE_USER = 'root'
DATABASE_HOST = 'localhost'
DATABASE_PORT = 3306
DATABASE_SCHEMA = "shopidentifyer"

STRIPE_CACHE_REFRESH_MINUTES=60

MAIL_SERVER = 'localhost'
MAIL_PORT = 22
MAIL_USE_TLS = True
MAIL_USE_SSL = False
MAIL_DEBUG = True

ACCESS_CONTROL_HOSTNAME = 'localhost'
ACCESS_CONTROL_SSH_PORT = 22
